package com.mercury.dao;

import com.mercury.dataobject.ItemDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Jan 11 21:16:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Jan 11 21:16:38 CST 2019
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Jan 11 21:16:38 CST 2019
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Jan 11 21:16:38 CST 2019
     */
    ItemDO selectByPrimaryKey(Integer id);

    // 查询所有商品信息并按照售销量倒序排列
    List<ItemDO> listItem();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Jan 11 21:16:38 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Jan 11 21:16:38 CST 2019
     */
    int updateByPrimaryKey(ItemDO record);

    int increaseSales(@Param(value = "itemId") Integer itemId, @Param(value = "amount") Integer amount);
}