
package com.mercury.review.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MobileAddressImpl", targetNamespace = "http://impl.server.webservice.review.mercury.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileAddressImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMobileAddress", targetNamespace = "http://impl.server.webservice.review.mercury.com/", className = "com.mercury.webservice.GetMobileAddress")
    @ResponseWrapper(localName = "getMobileAddressResponse", targetNamespace = "http://impl.server.webservice.review.mercury.com/", className = "com.mercury.webservice.GetMobileAddressResponse")
    @Action(input = "http://impl.server.webservice.review.mercury.com/MobileAddressImpl/getMobileAddressRequest", output = "http://impl.server.webservice.review.mercury.com/MobileAddressImpl/getMobileAddressResponse")
    public String getMobileAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
