
package com.mercury.review.webservice.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MobileAddressImplService", targetNamespace = "http://impl.server.webservice.review.mercury.com/", wsdlLocation = "http://192.168.220.1:8888/mobile?wsdl")
public class MobileAddressImplService
    extends Service
{

    private final static URL MOBILEADDRESSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MOBILEADDRESSIMPLSERVICE_EXCEPTION;
    private final static QName MOBILEADDRESSIMPLSERVICE_QNAME = new QName("http://impl.server.webservice.review.mercury.com/", "MobileAddressImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.220.1:8888/mobile?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOBILEADDRESSIMPLSERVICE_WSDL_LOCATION = url;
        MOBILEADDRESSIMPLSERVICE_EXCEPTION = e;
    }

    public MobileAddressImplService() {
        super(__getWsdlLocation(), MOBILEADDRESSIMPLSERVICE_QNAME);
    }

    public MobileAddressImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOBILEADDRESSIMPLSERVICE_QNAME, features);
    }

    public MobileAddressImplService(URL wsdlLocation) {
        super(wsdlLocation, MOBILEADDRESSIMPLSERVICE_QNAME);
    }

    public MobileAddressImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOBILEADDRESSIMPLSERVICE_QNAME, features);
    }

    public MobileAddressImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileAddressImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MobileAddressImpl
     */
    @WebEndpoint(name = "MobileAddressImplPort")
    public MobileAddressImpl getMobileAddressImplPort() {
        return super.getPort(new QName("http://impl.server.webservice.review.mercury.com/", "MobileAddressImplPort"), MobileAddressImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileAddressImpl
     */
    @WebEndpoint(name = "MobileAddressImplPort")
    public MobileAddressImpl getMobileAddressImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.server.webservice.review.mercury.com/", "MobileAddressImplPort"), MobileAddressImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOBILEADDRESSIMPLSERVICE_EXCEPTION!= null) {
            throw MOBILEADDRESSIMPLSERVICE_EXCEPTION;
        }
        return MOBILEADDRESSIMPLSERVICE_WSDL_LOCATION;
    }

}
